### ISSUE TITLE
START UP SOUND (Classic Era)

### ISSUE THREAD

**Issue by zburggg** [leatrix/leatrix-sounds#10]
### Issue

There is now a music playing on my WoW Classic since uninstalling and re-installing all the Leatrix. I also decided to install Leatrix Sounds and now I have what I'd describe as elevator music permanently playing when I load into WoW. Even after uninstalling the add-on. Please help, this is incredibly annoying.

### Game version

Classic Era

**Comment by zburggg** [comment]
This sound was coming from my system sounds in tray and as I had my PC muted while searching to see if there's programs that can find where sound is playing. I unmuted, the song must have played all the way through and now it has not played since. 

I'm unsure if this was related to leatrix but thanks and sorry if it wasn't.

**Comment by leatrix** [comment]
Just to confirm that it's not caused by Leatrix addons.  It looks like you found your answer though.
