### ISSUE TITLE
[REQUEST] mute sound option or copy to MuteSoundFile

### ISSUE THREAD

**Issue by vioray** [leatrix/leatrix-sounds#2]
it'd be great to be able to either have a tickbox on a sound to permanently mute it, or to right click it to automatically copy it into MuteSoundFile. I use the two addons together to find and stop the annoying sounds but it can sometimes take a while and a lot of typing if there's a few of them

**Comment by leatrix** [comment]
In Leatrix Sounds 10.0.25.alpha.x (latest alpha), you can hold control and left-click to print the selected track ID in chat or right-click to insert the selected track ID into the chat editbox (where you can then press CTRL/C to copy it to the clipboard).

In Leatrix Plus 10.0.26.alpha.x (latest alpha), there is a new option called 'Mute custom sounds' ('System').  Enter a list of sound IDs into the configuration panel (separated by comma) and click the Mute button.  That's all you need to do.  If you wish, you can enter a note next to the ID as a reminder of what the ID is for.

To switch to alpha releases, right-click the addon in CurseForge App and change the release type to alpha.  You can change it back to release anytime.
